spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 875252417126-u27937pmklm6i72bcoedum6bvb39418m.apps.googleusercontent.com
            client-secret: 4W85tnV-FiikeEoR-c9de50H
          facebook:
            client-id: 233247031518261
            client-secret: d6268f792fa5805e5e3f85563c2abe96
custom:
  oauth2:
    kakao:
      client-id: 519758